name: build

on:
  push:
    branches: [ master ]
    tags:
      - 'v*'
  pull_request:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (e.g., 1.3.5). Leave empty to skip release.'
        required: false
        default: ''

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        build_type: [RelWithDebInfo, Debug]
        ui: [gui, cli]
        scripting: [lua, noscripts]
        exclude:
          - build_type: Debug
            ui: gui
          - build_type: RelWithDebInfo
            ui: cli
          - build_type: RelWithDebInfo
            scripting: noscripts
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      # ... [all previous steps: install deps, skia, ccache, ninja, cmake, build, tests] ...

      - name: Upload Platform Artifact
        if: matrix.ui == 'gui' && matrix.scripting == 'lua' && matrix.build_type == 'RelWithDebInfo'
        uses: actions/upload-artifact@v4
        with:
          name: aseprite-${{ matrix.os }}
          path: build/bin/aseprite*

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag' || github.event.inputs.version != ''
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: List downloaded files
        run: |
          find artifacts -type f

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_type == 'tag' && github.ref_name || format('v{0}', github.event.inputs.version) }}
          name: Release ${{ github.ref_type == 'tag' && github.ref_name || format('v{0}', github.event.inputs.version) }}
          files: artifacts/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
