name: Build and Release Aseprite

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache Skia
        uses: actions/cache@v3
        id: skia-cache
        with:
          path: skia
          key: skia-v1

      - name: Download and install Skia
        if: steps.skia-cache.outputs.cache-hit != 'true'
        shell: powershell
        run: |
          $url = "https://skia.org/download/skia-win-x64.zip"
          $zipFile = "skia.zip"
          Invoke-WebRequest $url -OutFile $zipFile
          Expand-Archive -Path $zipFile -DestinationPath skia
          Remove-Item $zipFile

      - name: Cache OpenSSL
        uses: actions/cache@v3
        id: openssl-cache
        with:
          path: openssl
          key: openssl-3_5_2

      - name: Download and install OpenSSL
        if: steps.openssl-cache.outputs.cache-hit != 'true'
        shell: powershell
        run: |
          $url = "https://slproweb.com/download/Win64OpenSSL_Light-3_5_2.exe"
          $installer = "Win64OpenSSL.exe"
          Invoke-WebRequest $url -OutFile $installer
          Start-Process -FilePath $installer -ArgumentList "/silent /dir=$PWD/openssl" -Wait

      - name: Build Aseprite
        shell: powershell
        run: |
          # Your build commands here
          # Example:
          # .\build.bat

      - name: Zip build folder
        shell: powershell
        run: |
          Compress-Archive -Path build\* -DestinationPath build.zip

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: build.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
