name: Build Aseprite (Windows)

on:
  push:
    branches: [ main ]
    tags:
      - 'v*' # Runs when you push a version tag like v1.3.5
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (e.g., 1.3.5) — leave empty to skip release'
        required: false
        default: ''

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout Aseprite source
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies (CMake, Ninja)
        run: |
          choco install cmake ninja -y --installargs 'ADD_CMAKE_TO_PATH=System'

      - name: Download Skia prebuilt
        run: |
          curl -L -o skia.zip https://github.com/aseprite/skia/releases/download/m124-aseprite/skia-windows-Release-x64.zip
          mkdir skia
          tar -xf skia.zip -C skia
        shell: bash

      - name: Configure build
        shell: bash
        run: |
          mkdir build
          cd build
          cmake \
            -DCMAKE_BUILD_TYPE=RelWithDebInfo \
            -DLAF_BACKEND=skia \
            -DSKIA_DIR=${GITHUB_WORKSPACE}/skia \
            -DSKIA_LIBRARY_DIR=${GITHUB_WORKSPACE}/skia/out/Release-x64 \
            -DSKIA_LIBRARY=${GITHUB_WORKSPACE}/skia/out/Release-x64/skia.lib \
            -G Ninja \
            ..

      - name: Build
        run: |
          cd build
          ninja aseprite

      - name: Create Release
        if: github.ref_type == 'tag' || github.event.inputs.version != ''
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_type == 'tag' && github.ref_name || format('v{0}', github.event.inputs.version) }}
          name: Release ${{ github.ref_type == 'tag' && github.ref_name || format('v{0}', github.event.inputs.version) }}
          files: build/bin/aseprite.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
